title: CS221
description: Computer Science II
url: "https://shanep-cs2.github.io/"

theme: shanep-class
remote_teme: shanep/shanep-class
twitter_username: shanepanter
github_username:  shanep

exclude:
  - run-jekyll.sh
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

collections:
  lessons:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "course"